"""add summary column to announcements

Revision ID: aae37f7d0541
Revises: b057d4b48509
Create Date: 2026-05-02 04:59:54.659483
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aae37f7d0541'
down_revision: Union[str, None] = 'b057d4b48509'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcements', sa.Column('summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('announcements', 'summary')
    # ### end Alembic commands ###
