"""add announcement_id to pipeline_jobs

Revision ID: aec7f0aa570e
Revises: b057d4b48509
Create Date: 2026-05-02 03:05:52.005970
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aec7f0aa570e'
down_revision: Union[str, None] = 'b057d4b48509'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_jobs', sa.Column('announcement_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_pipeline_jobs_announcement_id'), 'pipeline_jobs', ['announcement_id'], unique=False)
    op.create_foreign_key(None, 'pipeline_jobs', 'announcements', ['announcement_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pipeline_jobs', type_='foreignkey')
    op.drop_index(op.f('ix_pipeline_jobs_announcement_id'), table_name='pipeline_jobs')
    op.drop_column('pipeline_jobs', 'announcement_id')
    # ### end Alembic commands ###
