"""initial tables

Revision ID: b057d4b48509
Revises: 
Create Date: 2026-04-08 13:20:38.863157
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b057d4b48509'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('organization', sa.String(length=200), nullable=True),
    sa.Column('executor', sa.String(length=200), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('target_text', sa.Text(), nullable=True),
    sa.Column('exclusion_text', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('detail_url', sa.Text(), nullable=True),
    sa.Column('extraction_status', sa.String(length=20), nullable=False),
    sa.Column('duplicate_of', sa.UUID(), nullable=True),
    sa.Column('raw_api_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['duplicate_of'], ['announcements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id', name='uq_announcements_source_source_id')
    )
    op.create_index(op.f('ix_announcements_extraction_status'), 'announcements', ['extraction_status'], unique=False)
    op.create_index(op.f('ix_announcements_source'), 'announcements', ['source'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('founded_date', sa.Date(), nullable=False),
    sa.Column('revenue', sa.BigInteger(), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('industry', sa.String(length=200), nullable=False),
    sa.Column('employee_count', sa.Integer(), nullable=False),
    sa.Column('ceo_birth_date', sa.Date(), nullable=False),
    sa.Column('certifications', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_edge_case', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipeline_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('fail_count', sa.Integer(), nullable=False),
    sa.Column('skip_count', sa.Integer(), nullable=False),
    sa.Column('error_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('announcement_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('download_url', sa.Text(), nullable=True),
    sa.Column('local_path', sa.Text(), nullable=True),
    sa.Column('converted_pdf_path', sa.Text(), nullable=True),
    sa.Column('conversion_status', sa.String(length=20), nullable=False),
    sa.Column('has_tables', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachments_announcement_id'), 'attachments', ['announcement_id'], unique=False)
    op.create_table('eligibility_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('announcement_id', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.String(length=50), nullable=False),
    sa.Column('condition_value', sa.Text(), nullable=False),
    sa.Column('condition_parsed', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('evidence_source', sa.Text(), nullable=True),
    sa.Column('processing_path', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eligibility_results_announcement_id'), 'eligibility_results', ['announcement_id'], unique=False)
    op.create_table('exclusion_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('announcement_id', sa.UUID(), nullable=False),
    sa.Column('exclusion_text', sa.Text(), nullable=False),
    sa.Column('evidence_source', sa.Text(), nullable=True),
    sa.Column('processing_path', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exclusion_results_announcement_id'), 'exclusion_results', ['announcement_id'], unique=False)
    op.create_table('match_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('announcement_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('company_value', sa.Text(), nullable=True),
    sa.Column('requirement_value', sa.Text(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('processing_path', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_match_ann_company', 'match_results', ['announcement_id', 'company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_match_ann_company', table_name='match_results')
    op.drop_table('match_results')
    op.drop_index(op.f('ix_exclusion_results_announcement_id'), table_name='exclusion_results')
    op.drop_table('exclusion_results')
    op.drop_index(op.f('ix_eligibility_results_announcement_id'), table_name='eligibility_results')
    op.drop_table('eligibility_results')
    op.drop_index(op.f('ix_attachments_announcement_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_table('pipeline_jobs')
    op.drop_table('companies')
    op.drop_index(op.f('ix_announcements_source'), table_name='announcements')
    op.drop_index(op.f('ix_announcements_extraction_status'), table_name='announcements')
    op.drop_table('announcements')
    # ### end Alembic commands ###
